groups:
- name: general
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Target {{ $labels.instance }} down"
      description: "Prometheus target {{ $labels.instance }} is down for 2 minutes."

  - alert: HighCPUNode
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU > 85% for >5m"

  - alert: LowDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100) < 10
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space on {{ $labels.instance }}"
      description: "Root filesystem <10% free for 10m"

  - alert: HTTPProbeFailure
    expr: probe_success == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "HTTP probe failed ({{ $labels.instance }})"
      description: "Blackbox probe failed for {{ $labels.instance }} for 2 minutes."


  - alert: MemoryHighNode
    expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "RAM > 85% por más de 10m"

  - alert: HttpLatencyHigh
    expr: histogram_quantile(0.95, sum(rate(probe_http_duration_seconds_bucket[5m])) by (le, instance)) > 1.5
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High HTTP latency (p95) on {{ $labels.instance }}"
      description: "p95 > 1.5s por 5 minutos"
