FROM node:20-alpine AS base
ENV NODE_ENV=production
WORKDIR /app
RUN corepack enable

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps ./apps
COPY libs ./libs
RUN pnpm install --frozen-lockfile

RUN pnpm -C apps/web build

EXPOSE 3000
CMD ["pnpm", "-C", "apps/web", "start", "-p", "3000"]
